# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
kotlin.code.style=official
kotlin.stdlib.default.dependency=false
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mc_version=1.19.2
forge_version=43.2.0

# https://github.com/JetBrains/kotlin
kotlin_version=2.2.21
# https://github.com/Kotlin/kotlinx.coroutines
coroutines_version=1.10.2
# https://github.com/Kotlin/kotlinx.serialization
serialization_version = 1.9.0
# https://github.com/Kotlin/kotlinx-atomicfu
atomicfu_version = 0.29.0
# https://github.com/Kotlin/kotlinx-datetime
datetime_version = 0.7.1
# https://github.com/Kotlin/kotlinx-io
io_version = 0.8.0